# Generated by Django 3.2.25 on 2024-10-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='ai_summary',
            field=models.TextField(null=True),
        ),
    ]
